spring:
  application:
    name: secure-employee-api

  profiles:
    active: dev

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: when_authorized

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  issuer: ${JWT_ISSUER}


refresh-token:
  expiration-millis: ${REFRESH_TOKEN_EXPIRATION}
  rotation-enabled: ${REFRESH_TOKEN_ROTATION_ENABLED}
  max-devices: ${REFRESH_TOKEN_MAX_DEVICES}
  reuse-detection: ${REFRESH_TOKEN_REUSE_DETECTION}
  revoke-on-password-change: ${REFRESH_TOKEN_REVOKE_ON_PASSWORD_CHANGE}
  cleanup-cron: ${REFRESH_TOKEN_CLEANUP_CRON}