spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: false

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true


logging:
  level:
    root: INFO

    com.khaled.secure_employee_api: DEBUG

    org.springframework.security: DEBUG

    org.hibernate.SQL: DEBUG